apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-blog
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /blog
        backend:
          serviceName: acme-blog
          servicePort: 80