apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-blog
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    haproxy.ingress.kubernetes.io/app-root: /$2    
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /blog(/|$)(.*)
        backend:
          serviceName: acme-blog
          servicePort: 80