apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-website-ingress
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /
        backend:
          serviceName: acme-website
          servicePort: 80