apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-blog
spec:
  rules:
  - host: blog.example.org
    http:
      paths:
      - path: /
        backend:
          serviceName: acme-blog
          servicePort: 80