apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-website
spec:
  selector:
    matchLabels:
      app: acme-website
  replicas: 1
  template:
    metadata:
      labels:
        app: acme-website
    spec:
      containers:
      - name: acme-website
        image: lmukadam/acmewebsite:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acme-website
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: acme-website
