apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: acme-blog
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /blog(/|$)(.*)
        backend:
          serviceName: acme-blog
          servicePort: 80