apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-blog-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /blog
        backend:
          serviceName: acme-blog
          servicePort: 80